# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_auto_20180102_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='facultad',
        ),
        migrations.AddField(
            model_name='aula',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universidad.Facultad'),
            preserve_default=False,
        ),
    ]
