# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoseccion',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matriculas.PeriodoAcademico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matriculas.CursoSeccion'),
            preserve_default=False,
        ),
    ]
