# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20180102_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoseccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
