# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_auto_20180102_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoseccion',
            old_name='alumno',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='cursoseccion',
            old_name='codigo',
            new_name='seccion',
        ),
    ]
