# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_auto_20180102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='promedio_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
